Add test for global let
mjarkk/general_programming_language pull request #2
Opened 2020-06-28 18:46 UTC by TheOtterlord

I've added the test and a `parse_str_fail` function. 
I couldn't think of any other fail tests to write yet, so have only added one. 

- Added a tester for false tests, where the code is meant to fail. 
- Added a test to confirm that a global let is properly addressed.

```
running 13 tests
test tests::test_empty ... ok
test tests::test_function_call_with_args ... FAILED
test tests::test_function_call ... FAILED
test tests::test_function_with_arg ... ok
test tests::test_function_with_args ... ok
test tests::test_function_with_arg_and_result ... FAILED
test tests::test_function_with_result ... FAILED
test tests::test_function_empty ... ok
test tests::test_functions_empty ... ok
test tests::test_variable ... FAILED
test tests::test_variable_global_let ... ok
test tests::test_variable_string_with_spaces ... FAILED
test tests::test_variable_strings_with_backslashes ... FAILED
```

2020-06-28 20:08 UTC, mjarkk requested changes
Thanks this is handy.  
i think the code could be a bit more rust like :)  

Here are some ways you can check a `Result` type:  
Using `match`: *(Recommended if you need to match more than 2 things or the match is somewhat complicated)*  
```rust
let res = Parser::parse(contents.into().as_bytes());
match res {
    Ok(res_value) => println!("value: {:?}", res_value),
    Err(err_message) => println!("error: {:?}", err_message),
}
```
Using `if let`: *(Recommended for cases like this)*  
```rust
let res = Parser::parse(contents.into().as_bytes());
if let Ok(res_value) = res{
    println!("value: {:?}", res_value);
}
```
Using generic programming methods, this is not recommended because one of rust it's biggest selling points is being a safe programming language and the above 2 are almost always better unless the safe methods make things too complicated without any reason.  
```rust
let res = Parser::parse(contents.into().as_bytes());
if res.is_ok() {
    println!("value: {:?}", res.unwrap()); // Unwrap gets the Ok value and if not exists it panics
}
```

2020-06-28 20:08 UTC, mjarkk commented on src/main.rs
> +    fn parse_str_fail(contents: impl Into<String>) -> Parser {
The `parse_str` function has the `-> Parser` as response because we can use that later on to verify the parsed content we don't need that here.  
```suggestion
    fn parse_str_fail(contents: impl Into<String>) {
```

2020-06-28 20:08 UTC, mjarkk commented on src/main.rs
> +        if res.is_ok() {
I think it's better to use `if let Ok(...) = .. ` here because then we use the variable inside the `Ok()` to printout, it's just a bit less bloated in the debug output because now it will also print Ok in the debug output.

```suggestion
        if let Ok(parsed_content) = res {
```

2020-06-28 20:08 UTC, mjarkk commented on src/main.rs
> +            panic!("{:?}", res);
If we use `if let Ok(...)` above we can change this to the variable inside the `Ok(..)`
```suggestion
            panic!("{:?}", parsed_content);
```

2020-06-28 20:08 UTC, mjarkk commented on src/main.rs
> +        } else {
This else block is not needed if we remove the response variable

2020-06-29 11:29 UTC, TheOtterlord commented
Revised the code. Thanks for the help

2020-06-29 11:37 UTC, mjarkk commented
Awesome!

2020-06-29 11:37 UTC, merged